name: Level 2 - Checkout & Run

on:
  push:
    branches: ["main"]

jobs:
  run-simple:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: action/checkout@v4

      - name: list file in repo
        run: ls -la

      - name: Run JS file
        run: node app.js
